variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  
build_and_install:
  stage: build
  script:
    - sphinx-build -M html . _build 
    - rsync -rt _build/html/ support@data.aimms.com:/home/aimms/www/how-to.aimms.com
  tags: 
    - ubuntu
  only:
    - master
  
pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - branches
